[programs.devnet]
myepicproject = "5fc4RHft5e8TBLzZMNSKaMHRZCNS9TDdRcapB9XoqgbY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/myia/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
